sudo: required
services:
  - docker

before_install:
  - docker build -t snaypssnp/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true snaypssnp/docker-react npm run test
deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  backet_name: "elasticbeanstalk-us-east-2-088050606175"
  backet_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
